### ISSUE TITLE
feat: Azure MSI authentication support

### ISSUE THREAD

**Issue by lukasmrtvy** [boltops-tools/terraspace_plugin_azurerm#6]
Would be nice to support also Azure MSI authentication. 

Terraform solution ( `ARM_USE_MSI=true` environment variable for fallbacking to MSI authentication ):
https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/managed_service_identity#configuring-managed-service-identity-in-terraform

Related:
https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/credentials/msi_token_provider.rb

Thanks

EDIT:  
CLI authentication is also useful imho ( `az login && terraspace ..` )
https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/credentials/azure_cli_token_provider.rb

**Comment by tongueroo** [comment]
Thanks for the links to the azure sdk. Dug into it and the ruby azure sdk was able to auth via MSI and CLI. Sadly, the azure ruby sdk has been deprecated:

https://github.com/Azure/azure-sdk-for-ruby/blob/master/docs/README.md

Have been able to get by still using the deprecated sdk for the terraspace_plugin_azurerm. Running into a few annoying issues with it though. IE:  It's gemspec pins faraday and other dependencies down, and microsoft is not updating the ruby gems. 

Resorted to writing a ruby gem that uses the Azure REST API https://github.com/boltops-tools/armrest  It was a bit of an effort 🤣

The armrest gem will check automatically check a few credentials 

    Environment -> MSI -> CLI

Note: Had some mixed feelings about the order of the auth provider chain. With AWS, the credentials provider chain puts the InstanceProfile at the end. See: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-precedence Feel this means more sense since need to make a network call to see if the metadata endpoint is available.

Studied the .net DefaultAzureCredential chain and based it on that. See: https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme#defaultazurecredential

Also, added docs: https://terraspace.cloud/docs/plugins/azure/auth/
